#!/bin/bash

chosen=$(echo -e "⏻ Apagar\n Reiniciar\n Cerrar sesión\n Bloquear" | \
  wofi --dmenu --style ~/.config/wofi/style.css --width 400 --height 275 --location 0 --cache-file /dev/null)

case "$chosen" in
  "⏻  Apagar") systemctl poweroff ;;
  "  Reiniciar") systemctl reboot ;;
  "  Cerrar sesión") hyprctl dispatch exit ;;
  "  Bloquear") hyprlock ;;
esac

